### ISSUE TITLE
support custom parsers/formatters and option to opt-out of our implementation

### ISSUE THREAD

**Issue by IgorKvasn** [AnnotationSro/ng-a-datepicker#1]
Right now, ng-a-datepicker depends on our own implementation of date parser/formatter. However it is common practice, that consuming application already has dependency on some date-manipulation library (Moment.js, Day.js,....).
Let's make it possible to opt-out of our date manipulation and use user's "custom" implementation.

The idea is to provide interface with parseDate and formatDate functions - if user passes this interface into ng-a-datepicker configuration, use that implementation, othwerise use our default implementation.

In case user provides their own implementation, **default implementation should not be included in the build**.

**Comment by Chiff** [comment]
This should be implemented with extraction of parsing utility to https://github.com/AnnotationSro/ng-a-parse

**Comment by Chiff** [comment]
ref to #OPN-2 / #OPN-12
